### PR TITLE
Removes Valid File Implimentation

### PR DESCRIPTION
**Pull request by SqueezyS**
This is useful so that you can transfer any file you want.

Limiting it to just standard files causes some bugs like in my Issue i submitted.

#30

### CODE REVIEW

**Comment by debrouxl** [comment]
If you've made sure that the file you've created is indeed correct and that you're transferring it to the appropriate calculator model, then the file format detection code might need a fix, though that's rather unlikely.
However, removing both file format checking and user feedback about an invalid file is quite a wrong way to address your immediate problem - the computer software world needs more checks, not fewer :)

**Comment by SqueezyS** [comment]
> If you've made sure that the file you've created is indeed correct and that you're transferring it to the appropriate calculator model, then the file format detection code might need a fix, though that's rather unlikely. However, removing both file format checking and user feedback about an invalid file is quite a wrong way to address your immediate problem - the computer software world needs more checks, not fewer :)

True, but limiting it to only TI exclusive files doesn't seem like a good idea in my opinion.

**Comment by adriweb** [comment]
Why? If it's invalid the calculator won't do anything with it anyway, if not straight up reject it.
If you've found a bug where a legitimate file could not be transferred, that would be worth fixing, as Lionel said!

**Comment by SqueezyS** [comment]
> Why? If it's invalid the calculator won't do anything with it anyway, if not straight up reject it. If you've found a bug where a legitimate file could not be transferred, that would be worth fixing, as Lionel said!

fair

**Pull request closed without merging**
